
spring:
  application:
    name: meme-service

  profiles: local

---

spring:
  profiles: cloud

  data:
    mongodb.uri: mongodb+srv://MemeService:<password>@cluster0-ppzjg.gcp.mongodb.net/test?retryWrites=true&w=majority
