
spring:

  application:
    name: meme-service

admin:
  username: admin
  password: adminPass

---

spring:
  profiles: cloud

  data:
    mongodb.uri: ${vcap.services.memservice-config.credentials.mongodb.uri}

admin:
  username: ${vcap.services.memservice-config.credentials.admin.username}
  password: ${vcap.services.memservice-config.credentials.admin.password}
